### ISSUE TITLE
Custom Dataset on Yolov10

### ISSUE THREAD

**Issue by yeongnamtan** [AarohiSingla/YOLOv10-Custom-Object-Detection#1]
# INFERENCE ON IMAGE
!yolo task=detect mode=predict conf=0.25 save=True model=runs/detect/train2/weights/best.pt source=test_image.jpg

I get below error when running the above command.  Appreciate any guidance on what could be wrong...

Ultralytics YOLOv8.1.34 🚀 Python-3.8.16 torch-1.12.1+cu113 CUDA:0 (Tesla T4, 14931MiB)
YOLOv10n summary (fused): 285 layers, 2694806 parameters, 0 gradients, 8.2 GFLOPs

Traceback (most recent call last):
  File "/opt/conda/bin/yolo", line 8, in <module>
    sys.exit(entrypoint())
  File "/opt/conda/lib/python3.8/site-packages/ultralytics/cfg/__init__.py", line 587, in entrypoint
    getattr(model, mode)(**overrides)  # default args from model
  File "/opt/conda/lib/python3.8/site-packages/ultralytics/engine/model.py", line 441, in predict
    return self.predictor.predict_cli(source=source) if is_cli else self.predictor(source=source, stream=stream)
  File "/opt/conda/lib/python3.8/site-packages/ultralytics/engine/predictor.py", line 177, in predict_cli
    for _ in gen:  # noqa, running CLI inference without accumulating any outputs (do not modify)
  File "/opt/conda/lib/python3.8/site-packages/torch/autograd/grad_mode.py", line 43, in generator_context
    response = gen.send(None)
  File "/opt/conda/lib/python3.8/site-packages/ultralytics/engine/predictor.py", line 255, in stream_inference
    self.results = self.postprocess(preds, im, im0s)
  File "/opt/conda/lib/python3.8/site-packages/ultralytics/models/yolo/detect/predict.py", line 25, in postprocess
    preds = ops.non_max_suppression(
  File "/opt/conda/lib/python3.8/site-packages/ultralytics/utils/ops.py", line 216, in non_max_suppression
    bs = prediction.shape[0]  # batch size
AttributeError: 'dict' object has no attribute 'shape'

**Comment by AarohiSingla** [comment]
Add
prediction = prediction['one2many'][0] to File "I:\Github\test\yolov10-main\yolov10-main\ultralytics\utils\ops.py", line 216, in non_max_suppression
bs = prediction.shape[0] # batch size

final code:

prediction = prediction['one2many'][0]
bs = prediction.shape[0]

**Comment by yeongnamtan** [comment]
> Add prediction = prediction['one2many'][0] to File "I:\Github\test\yolov10-main\yolov10-main\ultralytics\utils\ops.py", line 216, in non_max_suppression bs = prediction.shape[0] # batch size
> 
> final code:
> 
> prediction = prediction['one2many'][0] bs = prediction.shape[0]

Thank you so much.  It is working now.
