### ISSUE TITLE
AttributeError: 'str' object has no attribute 'view'

### ISSUE THREAD

**Issue by kasim-yildirim** [AarohiSingla/YOLOv10-Custom-Object-Detection#2]
Hello when I try to train my custom model I get following error, please help:

Traceback (most recent call last):
  File "c:\users\kasim\appdata\local\programs\python\python39\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "c:\users\kasim\appdata\local\programs\python\python39\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\kasim\AppData\Local\Programs\Python\Python39\Scripts\yolo.exe\__main__.py", line 7, in <module>
  File "c:\users\kasim\appdata\local\programs\python\python39\lib\site-packages\ultralytics\yolo\cfg\__init__.py", line 398, in entrypoint
    getattr(model, mode)(**overrides)  # default args from model
  File "c:\users\kasim\appdata\local\programs\python\python39\lib\site-packages\ultralytics\yolo\engine\model.py", line 371, in train
    self.trainer.train()
  File "c:\users\kasim\appdata\local\programs\python\python39\lib\site-packages\ultralytics\yolo\engine\trainer.py", line 192, in train
    self._do_train(world_size)
  File "c:\users\kasim\appdata\local\programs\python\python39\lib\site-packages\ultralytics\yolo\engine\trainer.py", line 330, in _do_train
    self.loss, self.loss_items = self.model(batch)
  File "c:\users\kasim\appdata\local\programs\python\python39\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "c:\users\kasim\appdata\local\programs\python\python39\lib\site-packages\ultralytics\nn\tasks.py", line 93, in forward
    return self.loss(x, *args, **kwargs)
  File "c:\users\kasim\appdata\local\programs\python\python39\lib\site-packages\ultralytics\nn\tasks.py", line 275, in loss
    return self.criterion(preds, batch)
  File "c:\users\kasim\appdata\local\programs\python\python39\lib\site-packages\ultralytics\utils\loss.py", line 200, in __call__
    pred_distri, pred_scores = torch.cat([xi.view(feats[0].shape[0], self.no, -1) for xi in feats], 2).split(
  File "c:\users\kasim\appdata\local\programs\python\python39\lib\site-packages\ultralytics\utils\loss.py", line 200, in <listcomp>
    pred_distri, pred_scores = torch.cat([xi.view(feats[0].shape[0], self.no, -1) for xi in feats], 2).split(
AttributeError: 'str' object has no attribute 'view'

**Comment by AarohiSingla** [comment]
https://github.com/THU-MIG/yolov10/issues/10
