### ISSUE TITLE
error while trying

### ISSUE THREAD

**Issue by Trooper-Pankaj** [AarohiSingla/YOLOv10-Custom-Object-Detection#4]
when I ran "**!yolo task=detect mode=predict conf=0.25 save=True model=../weights/yolov10n.pt source=../test_images/1.jpg"**
I was following each step of your video class
I got following error. please help, am I doing something wrong?

Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\insol\AppData\Local\Programs\Python\Python312\Scripts\yolo.exe\__main__.py", line 4, in <module>
  File "C:\Users\insol\AppData\Local\Programs\Python\Python312\Lib\site-packages\ultralytics\__init__.py", line 5, in <module>
    from ultralytics.data.explorer.explorer import Explorer
  File "C:\Users\insol\AppData\Local\Programs\Python\Python312\Lib\site-packages\ultralytics\data\explorer\explorer.py", line 18, in <module>
    from ultralytics.models.yolo.model import YOLO
  File "C:\Users\insol\AppData\Local\Programs\Python\Python312\Lib\site-packages\ultralytics\models\__init__.py", line 6, in <module>
    from .yolov10 import YOLOv10
  File "C:\Users\insol\AppData\Local\Programs\Python\Python312\Lib\site-packages\ultralytics\models\yolov10\__init__.py", line 1, in <module>
    from .model import YOLOv10
  File "C:\Users\insol\AppData\Local\Programs\Python\Python312\Lib\site-packages\ultralytics\models\yolov10\model.py", line 7, in <module>
    from huggingface_hub import PyTorchModelHubMixin
ModuleNotFoundError: No module named 'huggingface_hub'

**Comment by AarohiSingla** [comment]
pip install huggingface-hub

**Comment by Trooper-Pankaj** [comment]
Thanks a lot for previous solution. while I run **_"!yolo task=detect mode=predict conf=0.25 save=True model=../weights/yolov10l.pt source=../test_images/1.jpg_**

**I get the results perfectly fine but I get a warning**

ðŸ’¡ Learn more at https://docs.ultralytics.com/modes/predict
c:\users\insol\appdata\local\programs\python\python38\lib\site-packages\ultralytics\nn\tasks.py:733: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  ckpt = torch.load(file, map_location="cpu")

Could you please help in this, Thank you so much

**Comment by AarohiSingla** [comment]
You can ignore the warnings.
